---
- block:
  - name: add users to vboxusers group
    user:
      name: "{{ ansible_user_id }}"
      groups: vboxusers
      append: True
    notify: reload group permissions
  become: True
  become_user: root
...
